services:

  kopi:
    container_name: KOPI
    build: .
    volumes:
      - ./uassister:/var/www/html
    ports:
      - 8989:80
  
  mysql_database:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: kopi
  ports:
    - 3307:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9002:80
    environment:
      - PMA_ARBITRARY=1